sonar.projectKey=CryptoWatch
sonar.projectName=CryptoWatch
sonar.projectVersion=1.0

sonar.sources=app,components,hooks,lib,models,redux
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**