name: CryptoWatch CI

on:
  push:
    branches:
      - main
      - develop
      - features/add_LoadMoreButton

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build-and-sonar:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: SonarQube Scan
        shell: powershell
        run: |
          docker run --rm `
            -e SONAR_HOST_URL="http://host.docker.internal:9000" `
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" `
            -v "${{ github.workspace }}:/usr/src" `
            sonarsource/sonar-scanner-cli

      - name: Semgrep SAST Scan
        shell: powershell
        run: |
          docker run --rm `
            -v "${{ github.workspace }}:/src" `
            semgrep/semgrep `
            semgrep scan --config auto --json --output /src/semgrep-report.json /src

      - name: Upload Semgrep Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
          if-no-files-found: warn
